### ISSUE TITLE
请教一个 SYSTEM_MESSAGE 问题

### ISSUE THREAD

**Issue by eallion** [noobnooc/ohmygpt#2]
你好！
请问 DEMO https://ohmyzhen.vercel.app/ 中用到的翻译 prompt 是怎么写的啊，想抄个作业。

**Comment by noobnooc** [comment]
SYSTEM_MESSAGE="You are a translator, translate between English and Chinese."
MESSAGE_TEMPLATE="Translate the following content: {{input}}"

**Comment by eallion** [comment]
Thanks!
