### ISSUE TITLE
不知道为啥，api密钥总被提示泄露，具体的显示是泄漏到了github,vercel一更换密钥，密钥就被提示泄露禁用了。

### ISSUE THREAD

**Issue by xlxyq** [noobnooc/ohmygpt#4]
如题。

**Comment by xlxyq** [comment]
![image](https://github.com/assischat/ohmygpt/assets/32615715/a04c1042-cd65-4ef1-b1c5-dbbcbaad73d5)

**Comment by noobnooc** [comment]
有可能是在你自己 github 上的项目里包含 API Key 之类的。这个项目通过环境变量的方式注入的 Key 只要 Vercel 那边数据不泄露肯定是不会有问题的。

**Comment by xlxyq** [comment]
好的，谢谢，找到问题出处了，感谢回答。
